from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_adminFormWeb(object):
    def setupUi(self, adminFormWeb):
        adminFormWeb.setObjectName("adminFormWeb")
        adminFormWeb.resize(640, 500)
        adminFormWeb.setMinimumSize(QtCore.QSize(640, 500))
        adminFormWeb.setMaximumSize(QtCore.QSize(640, 500))
        self.centralwidget = QtWidgets.QWidget(parent=adminFormWeb)
        self.centralwidget.setObjectName("centralwidget")
        self.webTable = QtWidgets.QTableView(parent=self.centralwidget)
        self.webTable.setGeometry(QtCore.QRect(0, 0, 641, 300))
        self.webTable.setObjectName("webTable")
        self.selectPolz = QtWidgets.QComboBox(parent=self.centralwidget)
        self.selectPolz.setGeometry(QtCore.QRect(20, 340, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.selectPolz.setFont(font)
        self.selectPolz.setObjectName("selectPolz")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 310, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.deleteBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deleteBtn.setGeometry(QtCore.QRect(460, 330, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        self.deleteBtn.setFont(font)
        self.deleteBtn.setObjectName("deleteBtn")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 380, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.selectDate = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.selectDate.setGeometry(QtCore.QRect(20, 410, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        self.selectDate.setFont(font)
        self.selectDate.setObjectName("selectDate")
        adminFormWeb.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=adminFormWeb)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        adminFormWeb.setMenuBar(self.menubar)
        self.menuSotr = QtGui.QAction(parent=adminFormWeb)
        self.menuSotr.setObjectName("menuSotr")
        self.menuTime = QtGui.QAction(parent=adminFormWeb)
        self.menuTime.setObjectName("menuTime")
        self.menuPo = QtGui.QAction(parent=adminFormWeb)
        self.menuPo.setObjectName("menuPo")
        self.menuWeb = QtGui.QAction(parent=adminFormWeb)
        self.menuWeb.setObjectName("menuWeb")
        self.menu.addAction(self.menuSotr)
        self.menu.addAction(self.menuTime)
        self.menu.addAction(self.menuPo)
        self.menu.addAction(self.menuWeb)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(adminFormWeb)
        QtCore.QMetaObject.connectSlotsByName(adminFormWeb)

    def retranslateUi(self, adminFormWeb):
        _translate = QtCore.QCoreApplication.translate
        adminFormWeb.setWindowTitle(_translate("adminFormWeb", "Администрирование - Учет веб-ресурсов"))
        self.label.setText(_translate("adminFormWeb", "Выберите пользователя"))
        self.deleteBtn.setText(_translate("adminFormWeb", "Удалить"))
        self.label_4.setText(_translate("adminFormWeb", "Выберите дату"))
        self.menu.setTitle(_translate("adminFormWeb", "Администрирование"))
        self.menuSotr.setText(_translate("adminFormWeb", "Сотрудники"))
        self.menuTime.setText(_translate("adminFormWeb", "Рабочее время"))
        self.menuPo.setText(_translate("adminFormWeb", "Учет ПО"))
        self.menuWeb.setText(_translate("adminFormWeb", "Учет веб-ресурсов"))
