from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_adminFormPO(object):
    def setupUi(self, adminFormPO):
        adminFormPO.setObjectName("adminFormPO")
        adminFormPO.resize(640, 500)
        adminFormPO.setMinimumSize(QtCore.QSize(640, 500))
        adminFormPO.setMaximumSize(QtCore.QSize(640, 500))
        self.centralwidget = QtWidgets.QWidget(parent=adminFormPO)
        self.centralwidget.setObjectName("centralwidget")
        self.poTable = QtWidgets.QTableView(parent=self.centralwidget)
        self.poTable.setGeometry(QtCore.QRect(0, 0, 641, 300))
        self.poTable.setObjectName("tableView")
        self.selectPolz = QtWidgets.QComboBox(parent=self.centralwidget)
        self.selectPolz.setGeometry(QtCore.QRect(20, 340, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.selectPolz.setFont(font)
        self.selectPolz.setObjectName("selectPolz")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 310, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.deleteBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deleteBtn.setGeometry(QtCore.QRect(460, 330, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        self.deleteBtn.setFont(font)
        self.deleteBtn.setObjectName("updateTimeBtn")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(20, 380, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.selectDate = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.selectDate.setGeometry(QtCore.QRect(20, 410, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        self.selectDate.setFont(font)
        self.selectDate.setObjectName("selectDate")
        adminFormPO.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=adminFormPO)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 640, 21))
        self.menubar.setObjectName("menubar")
        self.menu = QtWidgets.QMenu(parent=self.menubar)
        self.menu.setObjectName("menu")
        adminFormPO.setMenuBar(self.menubar)
        self.menuSotr = QtGui.QAction(parent=adminFormPO)
        self.menuSotr.setObjectName("menuSotr")
        self.menuTime = QtGui.QAction(parent=adminFormPO)
        self.menuTime.setObjectName("menuTime")
        self.menuPo = QtGui.QAction(parent=adminFormPO)
        self.menuPo.setObjectName("menuPo")
        self.menuWeb = QtGui.QAction(parent=adminFormPO)
        self.menuWeb.setObjectName("menuWeb")
        self.menu.addAction(self.menuSotr)
        self.menu.addAction(self.menuTime)
        self.menu.addAction(self.menuPo)
        self.menu.addAction(self.menuWeb)
        self.menubar.addAction(self.menu.menuAction())

        self.retranslateUi(adminFormPO)
        QtCore.QMetaObject.connectSlotsByName(adminFormPO)

    def retranslateUi(self, adminFormPO):
        _translate = QtCore.QCoreApplication.translate
        adminFormPO.setWindowTitle(_translate("adminFormPO", "Администрирование - Учет ПО"))
        self.label.setText(_translate("adminFormPO", "Выберите пользователя"))
        self.deleteBtn.setText(_translate("adminFormPO", "Удалить"))
        self.label_4.setText(_translate("adminFormPO", "Выберите дату"))
        self.menu.setTitle(_translate("adminFormPO", "Администрирование"))
        self.menuSotr.setText(_translate("adminFormPO", "Сотрудники"))
        self.menuTime.setText(_translate("adminFormPO", "Рабочее время"))
        self.menuPo.setText(_translate("adminFormPO", "Учет ПО"))
        self.menuWeb.setText(_translate("adminFormPO", "Учет веб-ресурсов"))
