from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_adminFormTime(object):
    def setupUi(self, adminFormTime):
        adminFormTime.setObjectName("adminFormTime")
        adminFormTime.resize(900, 600)
        self.centralwidget = QtWidgets.QWidget(parent=adminFormTime)
        self.centralwidget.setObjectName("centralwidget")
        self.timeTable = QtWidgets.QTableView(parent=self.centralwidget)
        self.timeTable.setGeometry(QtCore.QRect(0, 0, 901, 300))
        self.timeTable.setObjectName("timeTable")
        self.selectPolz = QtWidgets.QComboBox(parent=self.centralwidget)
        self.selectPolz.setGeometry(QtCore.QRect(20, 340, 381, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.selectPolz.setFont(font)
        self.selectPolz.setObjectName("selectPolz")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 310, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 380, 231, 141))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.startTimeEdit = QtWidgets.QDateTimeEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        self.startTimeEdit.setFont(font)
        self.startTimeEdit.setDate(QtCore.QDate(2001, 1, 1))
        self.startTimeEdit.setObjectName("startTimeEdit")
        self.gridLayout.addWidget(self.startTimeEdit, 1, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.finishTimeEdit = QtWidgets.QDateTimeEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        self.finishTimeEdit.setFont(font)
        self.finishTimeEdit.setDate(QtCore.QDate(2001, 1, 1))
        self.finishTimeEdit.setObjectName("finishTimeEdit")
        self.gridLayout.addWidget(self.finishTimeEdit, 4, 0, 1, 1)
        self.deleteBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.deleteBtn.setGeometry(QtCore.QRect(690, 480, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        self.deleteBtn.setFont(font)
        self.deleteBtn.setObjectName("deleteBtn")
        self.addTimeBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addTimeBtn.setGeometry(QtCore.QRect(690, 330, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        self.addTimeBtn.setFont(font)
        self.addTimeBtn.setObjectName("addTimeBtn")
        self.clearBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clearBtn.setGeometry(QtCore.QRect(690, 430, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        self.clearBtn.setFont(font)
        self.clearBtn.setObjectName("clearBtn")
        self.label_4 = QtWidgets.QLabel(parent=self.centralwidget)
        self.label_4.setGeometry(QtCore.QRect(430, 310, 271, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.selectDate = QtWidgets.QDateEdit(parent=self.centralwidget)
        self.selectDate.setGeometry(QtCore.QRect(430, 340, 211, 31))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(16)
        self.selectDate.setFont(font)
        self.selectDate.setObjectName("selectDate")
        self.updateBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.updateBtn.setGeometry(QtCore.QRect(690, 380, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        self.updateBtn.setFont(font)
        self.updateBtn.setObjectName("updateBtn")
        adminFormTime.setCentralWidget(self.centralwidget)
        self.menubar = QtWidgets.QMenuBar(parent=adminFormTime)
        self.menubar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menubar.setObjectName("menubar")
        self.adminmenu = QtWidgets.QMenu(parent=self.menubar)
        self.adminmenu.setObjectName("adminmenu")
        adminFormTime.setMenuBar(self.menubar)
        self.menuSotr = QtGui.QAction(parent=adminFormTime)
        self.menuSotr.setObjectName("menuSotr")
        self.menuTime = QtGui.QAction(parent=adminFormTime)
        self.menuTime.setObjectName("menuTime")
        self.menuPo = QtGui.QAction(parent=adminFormTime)
        self.menuPo.setObjectName("menuPo")
        self.menuWeb = QtGui.QAction(parent=adminFormTime)
        self.menuWeb.setObjectName("menuWeb")
        self.adminmenu.addAction(self.menuSotr)
        self.adminmenu.addAction(self.menuTime)
        self.adminmenu.addAction(self.menuPo)
        self.adminmenu.addAction(self.menuWeb)
        self.menubar.addAction(self.adminmenu.menuAction())

        self.retranslateUi(adminFormTime)
        QtCore.QMetaObject.connectSlotsByName(adminFormTime)

    def retranslateUi(self, adminFormTime):
        _translate = QtCore.QCoreApplication.translate
        adminFormTime.setWindowTitle(_translate("adminFormTime", "Администрирование - Рабочее время"))
        self.label.setText(_translate("adminFormTime", "Выберите пользователя"))
        self.startTimeEdit.setDisplayFormat(_translate("adminFormTime", "HH:mm:ss"))
        self.label_2.setText(_translate("adminFormTime", "Начало рабочего дня"))
        self.label_3.setText(_translate("adminFormTime", "Окончание рабочего дня"))
        self.finishTimeEdit.setDisplayFormat(_translate("adminFormTime", "HH:mm:ss"))
        self.deleteBtn.setText(_translate("adminFormTime", "Удалить"))
        self.addTimeBtn.setText(_translate("adminFormTime", "Добавить"))
        self.clearBtn.setText(_translate("adminFormTime", "Очистить"))
        self.label_4.setText(_translate("adminFormTime", "Выберите дату"))
        self.updateBtn.setText(_translate("adminFormTime", "Изменить"))
        self.adminmenu.setTitle(_translate("adminFormTime", "Администрирование"))
        self.menuSotr.setText(_translate("adminFormTime", "Сотрудники"))
        self.menuTime.setText(_translate("adminFormTime", "Рабочее время"))
        self.menuPo.setText(_translate("adminFormTime", "Учет ПО"))
        self.menuWeb.setText(_translate("adminFormTime", "Учет веб-ресурсов"))
