from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_adminFormSotr(object):
    def setupUi(self, adminFormSotr):
        adminFormSotr.setObjectName("adminFormSotr")
        adminFormSotr.resize(900, 700)
        adminFormSotr.setMinimumSize(QtCore.QSize(900, 700))
        adminFormSotr.setMaximumSize(QtCore.QSize(900, 700))
        self.centralwidget = QtWidgets.QWidget(parent=adminFormSotr)
        self.centralwidget.setObjectName("centralwidget")
        self.polzTable = QtWidgets.QTableView(parent=self.centralwidget)
        self.polzTable.setGeometry(QtCore.QRect(0, 0, 900, 360))
        self.polzTable.setMinimumSize(QtCore.QSize(0, 0))
        self.polzTable.setMaximumSize(QtCore.QSize(1000, 1001))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.polzTable.setFont(font)
        self.polzTable.setObjectName("polzTable")
        self.addPolzBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.addPolzBtn.setGeometry(QtCore.QRect(720, 380, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        self.addPolzBtn.setFont(font)
        self.addPolzBtn.setObjectName("addPolzBtn")
        self.updatePolzBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.updatePolzBtn.setGeometry(QtCore.QRect(720, 430, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        self.updatePolzBtn.setFont(font)
        self.updatePolzBtn.setObjectName("updatePolzBtn")
        self.backBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.backBtn.setGeometry(QtCore.QRect(720, 600, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Kufi Arabic")
        font.setPointSize(14)
        self.backBtn.setFont(font)
        self.backBtn.setObjectName("backBtn")
        self.selectPolz = QtWidgets.QComboBox(parent=self.centralwidget)
        self.selectPolz.setGeometry(QtCore.QRect(20, 390, 381, 25))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.selectPolz.setFont(font)
        self.selectPolz.setObjectName("selectPolz")
        self.label = QtWidgets.QLabel(parent=self.centralwidget)
        self.label.setGeometry(QtCore.QRect(20, 370, 271, 16))
        font = QtGui.QFont()
        font.setFamily("Noto Mono")
        font.setPointSize(12)
        self.label.setFont(font)
        self.label.setObjectName("label")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(20, 420, 381, 244))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setObjectName("gridLayout")
        self.fEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.fEdit.setFont(font)
        self.fEdit.setObjectName("fEdit")
        self.gridLayout.addWidget(self.fEdit, 2, 0, 1, 1)
        self.label_2 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayout.addWidget(self.label_2, 0, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 5, 0, 1, 1)
        self.label_5 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 7, 0, 1, 1)
        self.iEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.iEdit.setFont(font)
        self.iEdit.setObjectName("iEdit")
        self.gridLayout.addWidget(self.iEdit, 4, 0, 1, 1)
        self.oEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.oEdit.setFont(font)
        self.oEdit.setObjectName("oEdit")
        self.gridLayout.addWidget(self.oEdit, 6, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 3, 0, 1, 1)
        self.doljEdit = QtWidgets.QLineEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.doljEdit.setFont(font)
        self.doljEdit.setObjectName("doljEdit")
        self.gridLayout.addWidget(self.doljEdit, 8, 0, 1, 1)
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.centralwidget)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(460, 420, 210, 112))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setObjectName("verticalLayout")
        self.supervisorCheck = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.supervisorCheck.setFont(font)
        self.supervisorCheck.setObjectName("supervisorCheck")
        self.verticalLayout.addWidget(self.supervisorCheck)
        self.adminCheck = QtWidgets.QCheckBox(parent=self.verticalLayoutWidget)
        self.adminCheck.setEnabled(True)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.adminCheck.setFont(font)
        self.adminCheck.setChecked(False)
        self.adminCheck.setObjectName("adminCheck")
        self.verticalLayout.addWidget(self.adminCheck)
        self.updatePasswordBtn = QtWidgets.QPushButton(parent=self.verticalLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(12)
        self.updatePasswordBtn.setFont(font)
        self.updatePasswordBtn.setObjectName("updatePasswordBtn")
        self.verticalLayout.addWidget(self.updatePasswordBtn)
        self.clearBtn = QtWidgets.QPushButton(parent=self.centralwidget)
        self.clearBtn.setGeometry(QtCore.QRect(720, 480, 150, 40))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        self.clearBtn.setFont(font)
        self.clearBtn.setObjectName("clearBtn")
        adminFormSotr.setCentralWidget(self.centralwidget)
        self.menuBar = QtWidgets.QMenuBar(parent=adminFormSotr)
        self.menuBar.setGeometry(QtCore.QRect(0, 0, 900, 21))
        self.menuBar.setObjectName("menuBar")
        self.menu = QtWidgets.QMenu(parent=self.menuBar)
        self.menu.setObjectName("menu")
        adminFormSotr.setMenuBar(self.menuBar)
        self.menuSotr = QtGui.QAction(parent=adminFormSotr)
        self.menuSotr.setObjectName("menuSotr")
        self.menuTime = QtGui.QAction(parent=adminFormSotr)
        self.menuTime.setObjectName("menuTime")
        self.menuPo = QtGui.QAction(parent=adminFormSotr)
        self.menuPo.setObjectName("menuPo")
        self.menuWeb = QtGui.QAction(parent=adminFormSotr)
        self.menuWeb.setObjectName("menuWeb")
        self.menu.addAction(self.menuSotr)
        self.menu.addAction(self.menuTime)
        self.menu.addAction(self.menuPo)
        self.menu.addAction(self.menuWeb)
        self.menuBar.addAction(self.menu.menuAction())

        self.retranslateUi(adminFormSotr)
        QtCore.QMetaObject.connectSlotsByName(adminFormSotr)

    def retranslateUi(self, adminFormSotr):
        _translate = QtCore.QCoreApplication.translate
        adminFormSotr.setWindowTitle(_translate("adminFormSotr", "Администрирование - Сотрудники"))
        self.addPolzBtn.setText(_translate("adminFormSotr", "Добавить"))
        self.updatePolzBtn.setText(_translate("adminFormSotr", "Изменить"))
        self.backBtn.setText(_translate("adminFormSotr", "Назад"))
        self.label.setText(_translate("adminFormSotr", "Выберите пользователя"))
        self.label_2.setText(_translate("adminFormSotr", "Фамилия"))
        self.label_4.setText(_translate("adminFormSotr", "Отчество"))
        self.label_5.setText(_translate("adminFormSotr", "Должность"))
        self.label_3.setText(_translate("adminFormSotr", "Имя"))
        self.supervisorCheck.setText(_translate("adminFormSotr", "Права руководителя"))
        self.adminCheck.setText(_translate("adminFormSotr", "Права администратора"))
        self.updatePasswordBtn.setText(_translate("adminFormSotr", "Изменить пароль"))
        self.clearBtn.setText(_translate("adminFormSotr", "Очистить"))
        self.menu.setTitle(_translate("adminFormSotr", "Администрирование"))
        self.menuSotr.setText(_translate("adminFormSotr", "Сотрудники"))
        self.menuTime.setText(_translate("adminFormSotr", "Рабочее время"))
        self.menuPo.setText(_translate("adminFormSotr", "Учет ПО"))
        self.menuWeb.setText(_translate("adminFormSotr", "Учет веб-ресурсов"))
