from PyQt6 import QtCore, QtGui, QtWidgets


class Ui_otchetForm(object):
    def setupUi(self, otchetForm):
        otchetForm.setObjectName("otchetForm")
        otchetForm.resize(840, 660)
        otchetForm.setMinimumSize(QtCore.QSize(840, 660))
        otchetForm.setMaximumSize(QtCore.QSize(840, 660))
        self.centralwidget = QtWidgets.QWidget(parent=otchetForm)
        self.centralwidget.setObjectName("centralwidget")
        self.otchetFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.otchetFrame.setGeometry(QtCore.QRect(0, 360, 331, 281))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        self.otchetFrame.setFont(font)
        self.otchetFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.otchetFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.otchetFrame.setObjectName("otchetFrame")
        self.verticalLayoutWidget = QtWidgets.QWidget(parent=self.otchetFrame)
        self.verticalLayoutWidget.setGeometry(QtCore.QRect(10, 40, 312, 121))
        self.verticalLayoutWidget.setObjectName("verticalLayoutWidget")
        self.verticalLayout = QtWidgets.QVBoxLayout(self.verticalLayoutWidget)
        self.verticalLayout.setContentsMargins(0, 0, 0, 0)
        self.verticalLayout.setSpacing(1)
        self.verticalLayout.setObjectName("verticalLayout")
        self.userReport = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.userReport.setObjectName("userReport")
        self.verticalLayout.addWidget(self.userReport)
        self.dayReport = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.dayReport.setObjectName("dayReport")
        self.verticalLayout.addWidget(self.dayReport)
        self.poReport = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.poReport.setObjectName("poReport")
        self.verticalLayout.addWidget(self.poReport)
        self.webReport = QtWidgets.QRadioButton(parent=self.verticalLayoutWidget)
        self.webReport.setObjectName("webReport")
        self.verticalLayout.addWidget(self.webReport)
        self.label = QtWidgets.QLabel(parent=self.otchetFrame)
        self.label.setGeometry(QtCore.QRect(10, 10, 261, 25))
        self.label.setObjectName("label")
        self.adminBtn = QtWidgets.QPushButton(parent=self.otchetFrame)
        self.adminBtn.setGeometry(QtCore.QRect(10, 180, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.adminBtn.setFont(font)
        self.adminBtn.setObjectName("adminBtn")
        self.exportBtn = QtWidgets.QPushButton(parent=self.otchetFrame)
        self.exportBtn.setGeometry(QtCore.QRect(10, 230, 291, 41))
        font = QtGui.QFont()
        font.setPointSize(12)
        self.exportBtn.setFont(font)
        self.exportBtn.setObjectName("exportBtn")
        self.userReportFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.userReportFrame.setGeometry(QtCore.QRect(330, 360, 511, 281))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        self.userReportFrame.setFont(font)
        self.userReportFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.userReportFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.userReportFrame.setObjectName("userReportFrame")
        self.label_2 = QtWidgets.QLabel(parent=self.userReportFrame)
        self.label_2.setGeometry(QtCore.QRect(10, 10, 291, 25))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.label_2.setFont(font)
        self.label_2.setObjectName("label_2")
        self.gridLayoutWidget = QtWidgets.QWidget(parent=self.userReportFrame)
        self.gridLayoutWidget.setGeometry(QtCore.QRect(10, 40, 491, 211))
        self.gridLayoutWidget.setObjectName("gridLayoutWidget")
        self.gridLayout = QtWidgets.QGridLayout(self.gridLayoutWidget)
        self.gridLayout.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout.setContentsMargins(0, 0, 0, 0)
        self.gridLayout.setSpacing(12)
        self.gridLayout.setObjectName("gridLayout")
        self.label_5 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_5.setFont(font)
        self.label_5.setObjectName("label_5")
        self.gridLayout.addWidget(self.label_5, 2, 1, 1, 1)
        self.lastDate = QtWidgets.QDateEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Georgian")
        self.lastDate.setFont(font)
        self.lastDate.setObjectName("lastDate")
        self.gridLayout.addWidget(self.lastDate, 3, 1, 1, 1)
        self.selectUser = QtWidgets.QComboBox(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectUser.setFont(font)
        self.selectUser.setObjectName("selectUser")
        self.gridLayout.addWidget(self.selectUser, 1, 0, 1, 2)
        self.fistDate = QtWidgets.QDateEdit(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Georgian")
        self.fistDate.setFont(font)
        self.fistDate.setObjectName("fistDate")
        self.gridLayout.addWidget(self.fistDate, 3, 0, 1, 1)
        self.pushButton = QtWidgets.QPushButton(parent=self.gridLayoutWidget)
        self.pushButton.setObjectName("pushButton")
        self.gridLayout.addWidget(self.pushButton, 4, 0, 1, 1)
        self.label_4 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_4.setFont(font)
        self.label_4.setObjectName("label_4")
        self.gridLayout.addWidget(self.label_4, 2, 0, 1, 1)
        self.label_3 = QtWidgets.QLabel(parent=self.gridLayoutWidget)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_3.setFont(font)
        self.label_3.setObjectName("label_3")
        self.gridLayout.addWidget(self.label_3, 0, 0, 1, 2)
        self.otchetTable = QtWidgets.QTableView(parent=self.centralwidget)
        self.otchetTable.setGeometry(QtCore.QRect(0, 0, 851, 360))
        self.otchetTable.setObjectName("otchetTable")
        self.dayReportFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.dayReportFrame.setGeometry(QtCore.QRect(330, 360, 511, 281))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        self.dayReportFrame.setFont(font)
        self.dayReportFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.dayReportFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.dayReportFrame.setObjectName("dayReportFrame")
        self.label_6 = QtWidgets.QLabel(parent=self.dayReportFrame)
        self.label_6.setGeometry(QtCore.QRect(10, 10, 291, 25))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.label_6.setFont(font)
        self.label_6.setObjectName("label_6")
        self.gridLayoutWidget_2 = QtWidgets.QWidget(parent=self.dayReportFrame)
        self.gridLayoutWidget_2.setGeometry(QtCore.QRect(10, 40, 491, 131))
        self.gridLayoutWidget_2.setObjectName("gridLayoutWidget_2")
        self.gridLayout_2 = QtWidgets.QGridLayout(self.gridLayoutWidget_2)
        self.gridLayout_2.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout_2.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_2.setSpacing(12)
        self.gridLayout_2.setObjectName("gridLayout_2")
        self.dayReportBtn = QtWidgets.QPushButton(parent=self.gridLayoutWidget_2)
        self.dayReportBtn.setObjectName("dayReportBtn")
        self.gridLayout_2.addWidget(self.dayReportBtn, 4, 0, 1, 1)
        self.label_8 = QtWidgets.QLabel(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_8.setFont(font)
        self.label_8.setObjectName("label_8")
        self.gridLayout_2.addWidget(self.label_8, 0, 0, 1, 2)
        self.reportDate = QtWidgets.QDateEdit(parent=self.gridLayoutWidget_2)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Georgian")
        self.reportDate.setFont(font)
        self.reportDate.setObjectName("reportDate")
        self.gridLayout_2.addWidget(self.reportDate, 1, 0, 1, 1)
        self.poReportFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.poReportFrame.setGeometry(QtCore.QRect(330, 360, 511, 281))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        self.poReportFrame.setFont(font)
        self.poReportFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.poReportFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.poReportFrame.setObjectName("poReportFrame")
        self.label_13 = QtWidgets.QLabel(parent=self.poReportFrame)
        self.label_13.setGeometry(QtCore.QRect(10, 10, 291, 25))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.label_13.setFont(font)
        self.label_13.setObjectName("label_13")
        self.gridLayoutWidget_4 = QtWidgets.QWidget(parent=self.poReportFrame)
        self.gridLayoutWidget_4.setGeometry(QtCore.QRect(10, 40, 491, 226))
        self.gridLayoutWidget_4.setObjectName("gridLayoutWidget_4")
        self.gridLayout_4 = QtWidgets.QGridLayout(self.gridLayoutWidget_4)
        self.gridLayout_4.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout_4.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_4.setSpacing(12)
        self.gridLayout_4.setObjectName("gridLayout_4")
        self.selectPoUser = QtWidgets.QComboBox(parent=self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectPoUser.setFont(font)
        self.selectPoUser.setObjectName("selectPoUser")
        self.gridLayout_4.addWidget(self.selectPoUser, 1, 0, 1, 2)
        self.poDate = QtWidgets.QDateEdit(parent=self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Georgian")
        self.poDate.setFont(font)
        self.poDate.setObjectName("poDate")
        self.gridLayout_4.addWidget(self.poDate, 3, 0, 1, 1)
        self.poReportBtn = QtWidgets.QPushButton(parent=self.gridLayoutWidget_4)
        self.poReportBtn.setObjectName("poReportBtn")
        self.gridLayout_4.addWidget(self.poReportBtn, 4, 0, 1, 1)
        self.label_16 = QtWidgets.QLabel(parent=self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_16.setFont(font)
        self.label_16.setObjectName("label_16")
        self.gridLayout_4.addWidget(self.label_16, 0, 0, 1, 2)
        self.label_15 = QtWidgets.QLabel(parent=self.gridLayoutWidget_4)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_15.setFont(font)
        self.label_15.setObjectName("label_15")
        self.gridLayout_4.addWidget(self.label_15, 2, 0, 1, 1)
        self.webReportFrame = QtWidgets.QFrame(parent=self.centralwidget)
        self.webReportFrame.setGeometry(QtCore.QRect(330, 360, 511, 281))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        font.setPointSize(14)
        self.webReportFrame.setFont(font)
        self.webReportFrame.setFrameShape(QtWidgets.QFrame.Shape.StyledPanel)
        self.webReportFrame.setFrameShadow(QtWidgets.QFrame.Shadow.Raised)
        self.webReportFrame.setObjectName("webReportFrame")
        self.label_19 = QtWidgets.QLabel(parent=self.webReportFrame)
        self.label_19.setGeometry(QtCore.QRect(10, 10, 291, 25))
        font = QtGui.QFont()
        font.setFamily("Noto Sans")
        self.label_19.setFont(font)
        self.label_19.setObjectName("label_19")
        self.gridLayoutWidget_6 = QtWidgets.QWidget(parent=self.webReportFrame)
        self.gridLayoutWidget_6.setGeometry(QtCore.QRect(10, 40, 491, 211))
        self.gridLayoutWidget_6.setObjectName("gridLayoutWidget_6")
        self.gridLayout_6 = QtWidgets.QGridLayout(self.gridLayoutWidget_6)
        self.gridLayout_6.setSizeConstraint(QtWidgets.QLayout.SizeConstraint.SetDefaultConstraint)
        self.gridLayout_6.setContentsMargins(0, 0, 0, 0)
        self.gridLayout_6.setSpacing(12)
        self.gridLayout_6.setObjectName("gridLayout_6")
        self.selectWebUser = QtWidgets.QComboBox(parent=self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.selectWebUser.setFont(font)
        self.selectWebUser.setObjectName("selectWebUser")
        self.gridLayout_6.addWidget(self.selectWebUser, 1, 0, 1, 2)
        self.webDate = QtWidgets.QDateEdit(parent=self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setFamily("Noto Sans Georgian")
        self.webDate.setFont(font)
        self.webDate.setObjectName("webDate")
        self.gridLayout_6.addWidget(self.webDate, 3, 0, 1, 1)
        self.webReportBtn = QtWidgets.QPushButton(parent=self.gridLayoutWidget_6)
        self.webReportBtn.setObjectName("webReportBtn")
        self.gridLayout_6.addWidget(self.webReportBtn, 4, 0, 1, 1)
        self.label_20 = QtWidgets.QLabel(parent=self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_20.setFont(font)
        self.label_20.setObjectName("label_20")
        self.gridLayout_6.addWidget(self.label_20, 2, 0, 1, 1)
        self.label_21 = QtWidgets.QLabel(parent=self.gridLayoutWidget_6)
        font = QtGui.QFont()
        font.setPointSize(12)
        self.label_21.setFont(font)
        self.label_21.setObjectName("label_21")
        self.gridLayout_6.addWidget(self.label_21, 0, 0, 1, 2)
        otchetForm.setCentralWidget(self.centralwidget)

        self.retranslateUi(otchetForm)
        QtCore.QMetaObject.connectSlotsByName(otchetForm)

    def retranslateUi(self, otchetForm):
        _translate = QtCore.QCoreApplication.translate
        otchetForm.setWindowTitle(_translate("otchetForm", "Отчеты"))
        self.userReport.setText(_translate("otchetForm", "Отчет по сотруднику"))
        self.dayReport.setText(_translate("otchetForm", "Отчет за выбранный день"))
        self.poReport.setText(_translate("otchetForm", "Отчет по используемому ПО"))
        self.webReport.setText(_translate("otchetForm", "Отчет по посещаемым сайтам"))
        self.label.setText(_translate("otchetForm", "Выберите тип отчета"))
        self.adminBtn.setText(_translate("otchetForm", "Администрирование"))
        self.exportBtn.setText(_translate("otchetForm", "Экспорт в Excel"))
        self.label_2.setText(_translate("otchetForm", "Рабочее время сотрудника"))
        self.label_5.setText(_translate("otchetForm", "Конец"))
        self.pushButton.setText(_translate("otchetForm", "Сформировать отчет"))
        self.label_4.setText(_translate("otchetForm", "Начало"))
        self.label_3.setText(_translate("otchetForm", "Выберите сотрудника"))
        self.label_6.setText(_translate("otchetForm", "Отчет за выбранный день"))
        self.dayReportBtn.setText(_translate("otchetForm", "Сформировать отчет"))
        self.label_8.setText(_translate("otchetForm", "Выберите дату"))
        self.label_13.setText(_translate("otchetForm", "Используемое ПО"))
        self.poReportBtn.setText(_translate("otchetForm", "Сформировать отчет"))
        self.label_16.setText(_translate("otchetForm", "Выберите сотрудника"))
        self.label_15.setText(_translate("otchetForm", "Выберите день"))
        self.label_19.setText(_translate("otchetForm", "Отчет по веб-ресурсам"))
        self.webReportBtn.setText(_translate("otchetForm", "Сформировать отчет"))
        self.label_20.setText(_translate("otchetForm", "Выберите день"))
        self.label_21.setText(_translate("otchetForm", "Выберите сотрудника"))
